### ISSUE TITLE
Group File Format

### ISSUE THREAD

**Issue by ripytide** [ripytide/pacdef#5]
My current best suggestion would be a single `pacdef.toml` file that looks like this:

```toml
[settings]
aur_helper = "paru"
[settings.hostnames]
home_pc = ["core", "cli_tools", "gui_tools"]
server_pc = ["core", "cli_tools"]

[groups.core]
arch = [
    "neovim",
    { package = "pacdef", optional_parameter = true },
]
apt = [
    "bat",
]

[groups.cli_tools]
arch = [
    "eza",
    "fzf",
]
```

This would replace the multiple group files from before with a single large `toml` file with multiple headings for the different groups. Also we can automate the group selection directly into the file by adding a `hostnames` section for specifying which groups should be active on which hostnames. Global settings can be configured in the `settings` section.

**Comment by ripytide** [comment]
I also think it's worth re-discussing the use-cases of per-package options since I'm not sure the use-cases initially provided are actually valid:
> Some packages, like pacdef itself, when installed from cargo, need feature flags to get some features. Similarly, pacman has optional dependencies that it may not install unless explicitly stated. These can be specified along with the package in the group file itself.

The first use-case no longer really applies since we no longer have any cargo features as we went back to cli-only for interacting with backends.
The second use-case of installing optional dependencies for archlinux packages seems just as possible or even more desirable to be fixed by manually adding the wanted optional dependencies into your package groups. See this reddit post for more details: https://www.reddit.com/r/archlinux/comments/1z9y3l/install_optional_dependencies/

**Comment by ripytide** [comment]
If we didn't need per-package install options that would simplify the file format quite a bit and make serializing/deserializing easier.

**Comment by InnocentZero** [comment]
> This would replace the multiple group files from before with a single large `toml` file with multiple headings for the different groups. 

I'm not sure if having one large file for configuration is a good idea. Usually people prefer to have multiple configuration files, and I think it'd be a good idea to have support for that.

> Also we can automate the group selection directly into the file by adding a `hostnames` section for specifying which groups should be active on which hostnames.

This sounds good to me.

> The first use-case no longer really applies since we no longer have any cargo features as we went back to cli-only for interacting with backends.

I believe it is still a very valid use-case for a number of backends. Having it in case of `arch` allows you to remember why you had it in the first place, something that wouldn't be possible using comments (I'm not sure if `toml-edit` preserves comments), `dnf` would have the `repo` option, allowing it to specify which repository, `flatpak` can have systemwide install or user install depending on packages, and rustup can have toolchains as packages with install options as their components and targets. This totally eliminates messups that are otherwise possible in the rustup format. There are still many cargo packages that have feature-enables or disables, and these flags can help.
And in case of `apt` it allows us to select a version (though the last one can probably be included in the package name itself).

**Comment by ripytide** [comment]
Fair, let's stick with multiple group files then. Wow, lots of pretty cool use-cases for per-package configs too so let's keep that too.

So the config/group files would look something like:

`config.toml`
```toml
aur_helper = "paru"

[hostnames]
home_pc = ["core", "cli_tools", "gui_tools"]
server_pc = ["core", "cli_tools"]
```

`groups/core.toml`
```toml
arch = [
    "neovim",
    { package = "pacdef", optional_parameter = true },
]
apt = [
    "bat",
]
```

`groups/cli_tools.toml`
```toml
arch = [
    "eza",
    "fzf",
]
```

`groups/gui_tools.toml`
```toml
arch = [
    "wayland",
]
```
