### ISSUE TITLE
Profiles (or group inheritance)

### ISSUE THREAD

**Issue by czuares** [ripytide/pacdef#68]
Thanks for this project! Would you consider implementing a feature that would allow a user to inherit/extend a group (or groups)?

I think this could be done by adding a special backend (ex: `_extends = ["desktop"]`) that is responsible for walking the tree to compile a list of packages from descendants. It would probably need some de-duplication logic as well in this mode.

For example, instead of having something like this:
```
[hostname_groups]
personal-laptop = [
  "system",
  "base",
  "interactive",
  "laptop",
  "wayland",
  "hyprland",
  "sway",
]
```

We could have something where:
`base` extends `system` 
`interactive` extends `base` 
`laptop` extends `interactive`
`sway` extends `wayland`
and so on.

So you would have a `config.toml` that looked like this:

```
personal-laptop = [
  "laptop",
  "hyprland",
  "sway",
]
```

If something like this is already possible, please let me know 🙂

**Comment by ripytide** [comment]
Dependency resolution between group files does sound like a cool feature. If I were to implement it I would probably add a `[metapac]` section to group files with a `dependencies = ["base", "wayland"]` key in it to allow for future per-group settings to be added.

However, I am reluctant to add such functionality since it would add quite a bit of complexity to the application, when personally I don't see that it's that much bother to manage the dependencies between package groups manually. For context here are is my current config:
```toml
disabled_backends = ["rustup"]

arch_package_manager = "paru"

hostname_groups_enabled = true

[hostname_groups]
archlaptop = ["base", "gui", "laptop", "cargo", "hyprland", "fonts", "dev"]
archpc = ["base", "gui", "cargo", "hyprland", "fonts", "dev"]
archserver = ["base", "archserver"]
```

There is certainly value in having dumb non-transitive group declarations such as these so you can tell exactly which group files are being applied to which computers.
And I can't imagine these lists ever growing so large that this manual dependency management would become too difficult.
